### ISSUE TITLE
Error: Unable to access jarfile flippertoproxmark3andback-v1.0.3.jar

### ISSUE THREAD

**Issue by mto3d** [tjamesw123/flipper-to-proxmark3-and-back#2]
Putting " java -jar flippertoproxmark3andback-v1.0.3.jar convert "E_unlk_1.nfc" export "proxmark3-dump.json"

returns

Error: Unable to access jarfile flippertoproxmark3andback-v1.0.3.jar

All files are in the same locations, most recent of java is installed, tried power shell, CMD and win+R and nothing happens, the .nfc is a ultralight ev1 it does have a password but it should be unlocked and I do have the password for it,

what am I doing wrong, could the usage have some iamges attached to show the instructions visualy ?

is there any way to take the ultralight EV1 data from my flipper and write it to a new blank EV1 card ?

**Comment by mto3d** [comment]
I also tried both codes on the readme page and both options returm the same error

**Comment by tjamesw123** [comment]
Ok I will look into it when I get the time, also I will include screen shots. And have you made sure the folder your in on terminal has the jar file in it? Dumb question on my part but thought I'd check.

**Comment by mto3d** [comment]
I belive so yes, I'll have a look and see.

**Comment by mto3d** [comment]
I did have a path issue and iv sorted it but now this is what is shown, issue with java versions ?

C:\Users\(my username) \Documents\Flipper Zero\NFC_01\xcon\New folder> java -jar flippertoproxmark3andback-v1.0.3.jar convert "E_unlk_1.nfc" export "proxmark3-dump.json"

Exception in thread "main" java.lang.UnsupportedClassVersionError: flippertoproxmark3andback/NfcDumpConverter has been compiled by a more recent version of the Java Runtime (class file version 64.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.access$100(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Source)

**Comment by mto3d** [comment]
or 

java -jar flippertoproxmark3andback-v1.0.3.jar convert "E_unlk_1.nfc" | "proxmark3-dump.json" export "T1.json"
'"proxmark3-dump.json"' is not recognized as an internal or external command,
operable program or batch file.

**Comment by tjamesw123** [comment]
Weird I'm going to test it on my end real quick now that I'm in the place to, this uses java 20 by the way

**Comment by tjamesw123** [comment]
Your completely right it isn't accessable

**Comment by tjamesw123** [comment]
I'm going to reexport the jar again and test if that one works

**Comment by mto3d** [comment]
thanks for the note about the java version, turns out i wasn't using java 20, followed a old download link to the java site, serched for java 20, found https://www.oracle.com/java/technologies/downloads/#jdk21-windows site for java 21, tried again in CMD promt, 

C:\Users\(my username) \Documents\Flipper Zero\NFC_01\xcon\New folder> java -jar flippertoproxmark3andback-v1.0.3.jar convert "E_unlk_1.nfc" export "proxmark3-dump.json" and got 

convert
E_unlk_1.nfc
export
proxmark3-dump.json
Convert!
E_unlk_1.nfc!
NFC!
RFIDCard!
MifareUltralight!
0004030101000B03
20
MFU11
Export!
proxmark3-dump.json!

so i think it's an issue with java version and the .jar file combined

**Comment by tjamesw123** [comment]
Actually I got it working right now, I will submit the screenshot, This is on verison 20.0.1 of java.
<img width="743" alt="How to screenshot for program" src="https://github.com/tjamesw123/flipper-to-proxmark3-and-back/assets/94910672/05f7b323-ad3e-4309-8b9f-2d4d4e098acf">

**Comment by tjamesw123** [comment]
Cool I'm going to say it's good I'm just going to add a note about the version and include the how to screenshot

**Comment by mto3d** [comment]
yeah I think it was java versions on my end, I used the old site https://www.java.com/download/ie_manual.jsp and it didnt work but with https://www.oracle.com/java/technologies/downloads/#jdk21-windows it worked, thanks for the fast response and help

**Comment by tjamesw123** [comment]
No problem now I know I should add a note to the read me
